### ISSUE TITLE
State of Charge right side tab not working

### ISSUE THREAD

**Issue by Reddragoneer1** [UCSolarCarTeam/Epsilon-Telemetry-Server#32]
The precharge state functions when off but should light up depending on the data given.

**Comment by bill-luu** [comment]
More description pls :)

**Comment by bill-luu** [comment]
When you say functions, does that mean stuff is changing?

Sounds like it's just always off

**Comment by henrytran28** [comment]
So when I just tested it with dummy values it worked fine. But because the server part never got implemented it always stays at the same value.

**Comment by Reddragoneer1** [comment]
Sure, that'd be great

**Comment by henrytran28** [comment]
So it was working right? I think that even though its duplicated in the Battery page the other pages don't have it and it might be useful to see it but that't up to you to decide.

**Comment by bill-luu** [comment]
Does it work then? If it doesn't, we should take some time to see if it's actually going to be a difficult fix, if it's just a matter of a small mistake, we might as well fix it. If it requires a ton of changes we can get rid of it. 

It'll be convenient to have just there as a quick reference.

Also for the record, I think page loading isn't really affected by internet speed, since this is a single page application (The entire website is loaded when we access it basically). But if there's bad internet, yeah we won't be getting updates.
