### ISSUE TITLE
Front end predictors

### ISSUE THREAD

**Issue by Reddragoneer1** [UCSolarCarTeam/Epsilon-Telemetry-Server#99]
Refer to image

**Comment by bill-luu** [comment]
Display the number of laps remaining, but instead of power remaining, replace with _battery time remaining_
![image](https://user-images.githubusercontent.com/15304203/59960282-9bfa2780-9483-11e9-80fd-5a4cb29d23e3.png)

https://docs.google.com/document/d/1Xl1AD5aZjhMhxXJ7C4tibxoxULANoSatnQI9HWPXwEY/edit?usp=sharing

**Comment by bill-luu** [comment]
The battery pack seconds remaining is already sent over via the lap service, so we just need to calculate the laps remaining.
